{% set version = "2.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rematch2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rematch2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rematch2/rematch2_{{ version }}.tar.gz
  sha256: d0423a418e8b46ac3a4819af7a7d19c39ca7c8c862c1e9a1c1294aa19152518f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-tibble
  run:
    - r-base
    - r-tibble

test:
  commands:
    - $R -e "library('rematch2')"           # [not win]
    - "\"%R%\" -e \"library('rematch2')\""  # [win]

about:
  home: https://github.com/r-lib/rematch2#readme
  license: MIT
  summary: Wrappers on 'regexpr' and 'gregexpr' to return the match results in tidy data frames.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: rematch2
# Title: Tidy Output from Regular Expression Matching
# Version: 2.1.0
# Authors@R: c( person("Gabor", "Csardi", email = "csardi.gabor@gmail.com", role = c("aut", "cre")), person("Matthew", "Lincoln", email = "matthew.d.lincoln@gmail.com", role = c("ctb")))
# Description: Wrappers on 'regexpr' and 'gregexpr' to return the match results in tidy data frames.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/rematch2#readme
# BugReports: https://github.com/r-lib/rematch2/issues
# RoxygenNote: 6.0.1
# Imports: tibble
# Suggests: covr, testthat
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-07-11 16:40:34 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Matthew Lincoln [ctb]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-11 17:32:41 UTC
